### ISSUE TITLE
SoapFault Parsing WSDL: Document is empty

### ISSUE THREAD

**Issue by dxvargas** [ec-europa/nexteuropa_poetry#11]
Maybe this is a misconfiguration on my side but anyway, some help is greatly appreciated, so I'm now creating this issue. When sending the translation request I get this error:

SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'build' : Document is empty in SoapClient->SoapClient() (line 43 of build/vendor/ec-europa/oe-poetry-client/src/Services/Providers/ServicesProvider.php).

**Comment by ademarco** [comment]
Thanks! Merged and closed.
